# Celegraph Travis CI Script

# See https://docs.travis-ci.com/user/getting-started/
# See https://docs.travis-ci.com/user/languages/cpp/
# See https://docs.travis-ci.com/user/reference/overview/
language: cpp
script: make && bin/test
compiler:
  - clang     # clang++
  - gcc       # g++
