# alpine - bash


# Base image
FROM alpine:3.6

# Set the working directory
WORKDIR /celegraph

# Copy the current directory contents into the container at the working directory
ADD . /celegraph

# --no-cache is like --update, but deletes package list cache automatically
# To search for valid packages, go to https://pkgs.alpinelinux.org/packages
RUN apk --no-cache add \
    bash \
    make\
    g++ \
    cmake \
    git \
    sqlite \
    sqlite-dev \
    sudo \
    vim

RUN ["make"]

# Make ports available to the world outside this container
# UDP ports need to be explicitly specified
# EXPOSE 1337
EXPOSE 1337/udp

# Spawn a command line interface
CMD ["bash"]